apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gabay-ingress
  namespace: gabay
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: gabay.janisrael.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gabay-service
            port:
              number: 80

