apiVersion: v1
kind: Service
metadata:
  name: gabay-service
  namespace: gabay
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 6003
    protocol: TCP
    name: http
  selector:
    app: gabay

